// frontend/src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "../providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let darkMode = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={darkMode ? "dark" : ""}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background text-text antialiased flex flex-col min-h-screen`}
      >
        <Providers>
          <Navbar />
          {/* 'grow' fills the space between Navbar and Footer.
              'flex flex-col' allows the children (your page content) 
              to use flex properties like justify-center to center themselves vertically.
          */}
          <main className="grow flex flex-col">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
